"use client";

import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";

type Team={id:string;name:string}; type Agent={id:string;fullName:string;workHours:12|24;teamIds:string[];periodByTeam:Record<string,"day"|"night"|"full">};
type Assignment={agentId:string;period:"day"|"night"|"full"};
export function ShiftForm({teams,agents}:{teams:Team[];agents:Agent[]}){
 const router=useRouter();const [serviceDate,setServiceDate]=useState("");const [teamId,setTeamId]=useState("");const [assignments,setAssignments]=useState<Assignment[]>([]);const [notes,setNotes]=useState("");const [saving,setSaving]=useState(false);const [message,setMessage]=useState("");
 function selectTeam(id:string){setTeamId(id);setAssignments(agents.filter(a=>a.teamIds.includes(id)).map(a=>({agentId:a.id,period:a.periodByTeam[id]??(a.workHours===24?"full":"day")})))}
 function toggleAgent(agent:Agent){setAssignments(c=>c.some(x=>x.agentId===agent.id)?c.filter(x=>x.agentId!==agent.id):[...c,{agentId:agent.id,period:agent.periodByTeam[teamId]??(agent.workHours===24?"full":"day")}])}
 async function submit(e:FormEvent){e.preventDefault();setSaving(true);setMessage("");try{const r=await fetch("/api/admin/shifts",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({serviceDate,teamId,assignments,notes})});const j=await r.json();if(!r.ok)throw new Error(j.error??"Falha ao criar plantão.");router.push("/admin/escalas");router.refresh();}catch(err){setMessage(err instanceof Error?err.message:"Erro.");}finally{setSaving(false)}}
 const teamAgents=agents.filter(a=>a.teamIds.includes(teamId));
 return <form className="card shift-form" onSubmit={submit}><div className="grid grid-2"><div className="field"><label className="label">Data do plantão</label><input className="input" type="date" value={serviceDate} onChange={e=>setServiceDate(e.target.value)} required/><span className="field-help">07h desta data até 07h do dia seguinte.</span></div><div className="field"><label className="label">Equipe</label><select className="select" value={teamId} onChange={e=>selectTeam(e.target.value)} required><option value="">Selecione...</option>{teams.map(t=><option value={t.id} key={t.id}>{t.name}</option>)}</select></div></div><div className="field"><label className="label">Observações</label><textarea className="textarea" value={notes} onChange={e=>setNotes(e.target.value)}/></div>{teamId&&<><div className="form-section-title">Agentes da equipe</div><div className="notice notice-success">Todos os agentes cadastrados nesta equipe já foram selecionados automaticamente. Desmarque apenas quem não trabalhará neste plantão.</div><div className="team-checkbox-grid">{teamAgents.map(a=>{const item=assignments.find(x=>x.agentId===a.id);return <div className="team-checkbox" key={a.id}><input type="checkbox" checked={Boolean(item)} onChange={()=>toggleAgent(a)}/><div style={{flex:1}}><strong>{a.fullName}</strong><div className="field-help">Jornada {a.workHours}h</div></div>{item&&<select className="select" style={{width:145}} value={item.period} disabled={a.workHours===24} onChange={e=>setAssignments(c=>c.map(x=>x.agentId===a.id?{...x,period:e.target.value as Assignment["period"]}:x))}>{a.workHours===24?<option value="full">07–07</option>:<><option value="day">07–19</option><option value="night">19–07</option></>}</select>}</div>})}</div></>}{message&&<div className="notice notice-error">{message}</div>}<div className="form-actions"><button type="button" className="button button-secondary" onClick={()=>router.back()}>Cancelar</button><button className="button" disabled={saving}>{saving?"Salvando...":"Criar plantão"}</button></div></form>
}
