"use client";

import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { normalizePlate } from "@/lib/utils/format";

type Initial = { plate: string; vehicleType: string; brandModel: string; color: string; companyName: string; fleetPrefix: string; routeName: string; notes: string; active: boolean };
export function VehicleForm({ initial }: { initial?: Initial }) {
  const router=useRouter(); const editing=Boolean(initial);
  const [plate,setPlate]=useState(initial?.plate??""); const [vehicleType,setVehicleType]=useState(initial?.vehicleType??"Carro"); const [brandModel,setBrandModel]=useState(initial?.brandModel??""); const [color,setColor]=useState(initial?.color??"");
  const [companyName,setCompanyName]=useState(initial?.companyName??""); const [fleetPrefix,setFleetPrefix]=useState(initial?.fleetPrefix??""); const [routeName,setRouteName]=useState(initial?.routeName??""); const [notes,setNotes]=useState(initial?.notes??""); const [active,setActive]=useState(initial?.active??true); const [saving,setSaving]=useState(false); const [message,setMessage]=useState("");
  async function submit(e:FormEvent){e.preventDefault();setSaving(true);setMessage("");try{const r=await fetch(editing?`/api/admin/vehicles/${initial!.plate}`:"/api/admin/vehicles",{method:editing?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({plate:normalizePlate(plate),vehicleType,brandModel,color,companyName,fleetPrefix,routeName,notes,active})});const j=await r.json();if(!r.ok)throw new Error(j.error??"Falha ao salvar veículo.");router.push("/admin/veiculos");router.refresh();}catch(err){setMessage(err instanceof Error?err.message:"Erro.");}finally{setSaving(false);}}
  return <form className="card" onSubmit={submit}><div className="grid grid-2"><div className="field"><label className="label">Placa</label><input className="input" value={plate} onChange={e=>setPlate(normalizePlate(e.target.value))} disabled={editing} placeholder="ABC1D23" required/></div><div className="field"><label className="label">Tipo</label><select className="select" value={vehicleType} onChange={e=>setVehicleType(e.target.value)}><option>Carro</option><option>Ônibus</option><option>Van</option><option>Táxi</option><option>Moto</option><option>Micro-ônibus</option><option>Outro</option></select></div><div className="field"><label className="label">Marca / modelo</label><input className="input" value={brandModel} onChange={e=>setBrandModel(e.target.value)}/></div><div className="field"><label className="label">Cor</label><input className="input" value={color} onChange={e=>setColor(e.target.value)}/></div><div className="field"><label className="label">Empresa / operador</label><input className="input" value={companyName} onChange={e=>setCompanyName(e.target.value)}/></div><div className="field"><label className="label">Prefixo</label><input className="input" value={fleetPrefix} onChange={e=>setFleetPrefix(e.target.value)}/></div><div className="field"><label className="label">Linha</label><input className="input" value={routeName} onChange={e=>setRouteName(e.target.value)}/></div><div className="field"><label className="label">Status</label><select className="select" value={active?"active":"inactive"} onChange={e=>setActive(e.target.value==="active")}><option value="active">Ativo</option><option value="inactive">Inativo</option></select></div></div><div className="field"><label className="label">Observações</label><textarea className="textarea" value={notes} onChange={e=>setNotes(e.target.value)}/></div>{message&&<div className="notice notice-error">{message}</div>}<div className="form-actions"><button type="button" className="button button-secondary" onClick={()=>router.back()}>Cancelar</button><button className="button" disabled={saving}>{saving?"Salvando...":"Salvar veículo"}</button></div></form>
}
